In [2]:
import numpy as np

### search non-zero entries

In [3]:
x = np.array([[1,0,0], [0,2,0], [1,1,0]])

In [7]:
np.nonzero(x)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [8]:
x[np.nonzero(x)]

array([1, 2, 1, 1])

In [9]:
np.transpose(np.nonzero(x))

array([[0, 0],
       [1, 1],
       [2, 0],
       [2, 1]], dtype=int64)

### select entries with threshold 

In [11]:
np.nonzero(x > 1)

(array([1], dtype=int64), array([1], dtype=int64))

In [12]:
x[x > 10] = 0

In [ ]:
from pandas import DataFrame
DataFrame(lane_line_img).to_csv('lane_contour_img.csv', sep=',', encoding='utf-8')

In [ ]:
pts = np.array([[100,50],[200,300],[70,20],[500,100]], np.int32)
pts = pts.reshape((-1,1,2))
print (pts)
cv2.polylines(blurred_img,[pts],True,(255,0,0))
plt.imshow(blurred_img)

### fit the line 

In [3]:
from scipy import stats

In [4]:
x = [2, 5, 7]
y = [15, 33, 45]

In [5]:
slope, intercept, _, _, std_err = stats.linregress(x,y)

In [7]:
print (slope, intercept)
print ("format is y = slope * x + intercept")

6.0 3.0
format is y = slope * x + intercept


In [ ]:
# collect_img = np.copy(img)
# ############
# collect_img = np.concatenate((collect_img, np.stack(((masked_image,) * 3), axis=2)), axis=0)
# ############        
# print ("OK 3")

# ############
# collect_img = np.concatenate((collect_img, line_img), axis=0)
# ############     
# plt.imshow(collect_img)

In [ ]:
_img = mpimg.imread("test_images/" + os.listdir("test_images/")[])
img = np.copy(_img)
#################################
imshape = img.shape

gray_img = grayscale(img) # output an image with only one color channel

low_threshold = 50
high_threshold = 200
canny_img = canny(gray_img, low_threshold, high_threshold)

kernel_size = 1
blurred_img = gaussian_blur(canny_img, kernel_size)

rho = 1
theta = np.pi/180
threshold = 15
min_line_len = 40
max_line_gap = 5
line_img = hough_lines(blurred_img, rho, theta, threshold, min_line_len, max_line_gap) 
plt.imshow(line_img)

vertices = np.array([[(0,imshape[0]),(450, imshape[0]//2), (490, imshape[0]//2), (imshape[1],imshape[0])]], dtype=np.int32)
masked_image = region_of_interest(line_img, vertices)
# plt.imshow(masked_image)

x,y = np.nonzero(masked_image[:,:,0])
apex_y, apex_x = fit_parabola(x, y)

# print (apex_y, apex_x)
leftLane_img = np.copy(laneline_img_copy[int(apex_y):,:int(apex_x)])
RightLane_img = np.copy(laneline_img_copy[int(apex_y):,int(apex_x):])

# plt.imshow(leftLane_img)
# plt.imshow(RightLane_img)

x1_left, x2_left = fit_Lane(leftLane_img)
x1_right, x2_right = fit_Lane(RightLane_img)

lines = [(x1_left, int(apex_y), x2_left, imshape[0]), (x1_right + int(apex_x), int(apex_y), x2_right + int(apex_x), imshape[0])]
withLine_img = np.zeros_like(img)
draw_lines(withLine_img, lines, thickness=7)
# plt.imshow(withLine_img)
plt.imshow(weighted_img(line_img, img))