In [2]:
import numpy as np

### search non-zero entries

In [3]:
x = np.array([[1,0,0], [0,2,0], [1,1,0]])

In [7]:
np.nonzero(x)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [8]:
x[np.nonzero(x)]

array([1, 2, 1, 1])

In [9]:
np.transpose(np.nonzero(x))

array([[0, 0],
       [1, 1],
       [2, 0],
       [2, 1]], dtype=int64)

### select entries with threshold 

In [11]:
np.nonzero(x > 1)

(array([1], dtype=int64), array([1], dtype=int64))

In [12]:
x[x > 10] = 0

In [ ]:
from pandas import DataFrame
DataFrame(lane_line_img).to_csv('lane_contour_img.csv', sep=',', encoding='utf-8')

In [ ]:
pts = np.array([[100,50],[200,300],[70,20],[500,100]], np.int32)
pts = pts.reshape((-1,1,2))
print (pts)
cv2.polylines(blurred_img,[pts],True,(255,0,0))
plt.imshow(blurred_img)